### ISSUE TITLE
Part 2, question 1 (Formatting)

### ISSUE THREAD

**Issue by ghost** [DevMountain/intermediate-javascript-assessment#7]
Formatting issue: We should consider telling the student that the $http request will return an array of user objects.  We imply it from what we ask, but it's not obvious, and the current wording could confuse them.

**Comment by asBrettisay** [comment]
I agree, this is very confusing the way it is prompted.

Maybe the example of the return data should also show that users are going to be sent back?

**Comment by r-walsh** [comment]
:+1: Addressing in #16
